spring.application.name=backend

#Server
server.port=8080
server.servlet.context-path=/api

#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/real_estate_dev_db
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog-master.yaml

# JWT
# Open application.properties and change this line:
app.jwt.secret-key=${JWT_SECRET:4qVb7xRkW9zP1mN8sT2vX5yZ3cBcDeFgHiJkLmNoPqR}
app.jwt.access-token-expiration-minutes=90
app.jwt.refresh-token-expiration-days=18

# File upload
#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=20MB
#app.upload.dir=uploads/properties

# Swagger / Open API
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.realestate.backend.controller

spring.devtools.restart.enabled=false

# Hikari connection pool
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.connection-timeout=20000
#spring.datasource.hikari.max-lifetime=1200000

# Logging
#logging.level.com.estateflow=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Dev Tools
#spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true